### ISSUE TITLE
Plowdown not working with 1fichier.com

### ISSUE THREAD

**Issue by juanlucky** [Alexis38/plowshare4#1]
Hello, since the addition of an alert message on the 1fichier.com pages, the download (connected with a user) of a file does not work.
Error : parse failed (sed): "/Filename.."
Failed inside 1fichier_download line 84, 1fichier.sh

**Comment by Alexis38** [comment]
Hi, what the URL ?
Use the httpS  ?

**Comment by juanlucky** [comment]
Sorry : tested for example with https://1fichier.com/?2vkds2zmha
Yes https

**Comment by Alexis38** [comment]
I go test on 5-10 min.

Thank you

**Comment by Alexis38** [comment]
I just change the 1fichier.sh file (https://github.com/Alexis38/plowshare4/blob/master/modules/1fichier.sh)

Re-download the file, and update now

**Comment by juanlucky** [comment]
Well done Alexis! it works again.
Thanks a lot for such reactivity !

**Comment by Alexis38** [comment]
Your welcome ^^

**Comment by juanlucky** [comment]
Fixed
