### ISSUE TITLE
[1fichier] old url format not accepted 

### ISSUE THREAD

**Issue by juanlucky** [Alexis38/plowshare4#2]
Hi
I tried to dl 2 files with this url schema on 1 fichier.com :
#NOMODULE https://bk6mgr.1fichier.com/
#NOMODULE https://wyvxo7a2px.1fichier.com/

Wich seems to be an older one than https://1fichier.com/?tog2rklfxq and is accepted.

Plowdown doesn't find the 1fichier module.
Thanks for your help.

**Comment by Alexis38** [comment]
Hello,

Can you please send your command ?


Thank you

**Comment by juanlucky** [comment]
The cmd is

plowdown -a user:pwd -m /media/STORAGE/download/01-dl.list --outp
ut-directory=/media/STORAGE/download --temp-dir
ectory=/media/STORAGE/download/tmp -v4 &> debug
.log

With file dl.lst containing 2 "old" url schema and 1 new one wich is working

#NOMODULE https://bk6mgr.1fichier.com/
#NOMODULE https://wyvxo7a2px.1fichier.com/
https://1fichier.com/?84sr8se6tj


Here is the debug logs 

rep: === SYSTEM INFO BEGIN ===
rep: [mach] geexbox armv7 linux-gnueabihf armv7-openbricks-linux-gnueabihf
rep: [bash] 4.3.0(1)-release
rep: [curl] curl 7.34.0 (armv7-openbricks-linux-gnueabihf) libcurl/7.34.0 OpenSSL/1.0.1g zlib/1.2.8
rep: [sed ] This is not GNU sed version 4.0
rep: [lib ] '/root/plowshare4'
rep: === SYSTEM INFO END ===
rep: plowdown version GIT-snapshot
Temporary directory: /media/STORAGE/download/tmp
Output directory: /media/STORAGE/download
No module found, try simple redirection
rep: --insecure --compressed --speed-time 600 --connect-timeout 240 --silent --user-agent  --head https://bk6mgr.1fichier.com/
rep: Received 247 bytes. DRETVAL=0
rep: === CURL BEGIN ===
rep:HTTP/1.1 200 OK
rep:Server: nginx
rep:Date: Wed, 28 Oct 2015 09:36:37 GMT
rep:Content-Type: text/html; charset=utf-8
rep:Connection: keep-alive
rep:Vary: Accept-Encoding
rep:Cache-Control: no-cache
rep:Expires: Fri, 30 Oct 1998 14:19:41 GMT
rep:Content-Encoding: gzip
rep:
rep: === CURL END ===
dbg: remote server reply: HTTP/1.1 200 OK
Skip: no module for URL (https://bk6mgr.1fichier.com/)
link marked in file `/media/STORAGE/download/01-dl.list' (#NOMODULE)
No module found, try simple redirection
rep: --insecure --compressed --speed-time 600 --connect-timeout 240 --silent --user-agent  --head https://wyvxo7a2px.1fichier.com/
rep: Received 247 bytes. DRETVAL=0
rep: === CURL BEGIN ===
rep:HTTP/1.1 200 OK
rep:Server: nginx
rep:Date: Wed, 28 Oct 2015 09:36:41 GMT
rep:Content-Type: text/html; charset=utf-8
rep:Connection: keep-alive
rep:Vary: Accept-Encoding
rep:Cache-Control: no-cache
rep:Expires: Fri, 30 Oct 1998 14:19:41 GMT
rep:Content-Encoding: gzip
rep:
rep: === CURL END ===
dbg: remote server reply: HTTP/1.1 200 OK
Skip: no module for URL (https://wyvxo7a2px.1fichier.com/)
link marked in file `/media/STORAGE/download/01-dl.list' (#NOMODULE)
Starting download (1fichier): https://1fichier.com/?84sr8se6tj
Starting login process: xxxxx/*******
rep: --insecure --compressed --speed-time 600 --connect-timeout 240 --user-agent Mozilla/5.0 (X11; Linux x86_64; rv:6.0) Gecko/20100101 Firefox/6.0 --silent --cookie-jar /media/STORAGE/download/tmp/plowdown.9489.17028 --data mail=xxxxxx&pass=xxxxx&lt=on&purge=on&secure=on&Login=Login https://1fichier.com/login.pl?lg=en
rep: Received 7446 bytes. DRETVAL=0
rep: === CURL BEGIN ===
rep:<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN"
rep:	"http://www.w3.org/TR/html4/strict.dtd">
rep:<html lang="fr">
rep:<head>
rep:  <title>1fichier.com: Cloud Storage</title>
rep:  <meta http-equiv="content-type" content="text/html;charset=utf-8">
rep:  <link rel="stylesheet" href="https://img.1fichier.com/css/style.css" type="text/css">
rep:  <link href="https://img.1fichier.com/css/jquery.ui.css" rel="stylesheet" type="text/css" media="screen">
rep:  <script type="text/javascript" src="https://img.1fichier.com/js/jquery.js"></script>
rep:	<script type="text/javascript">jQuery(document).ready(function($) {window.location = 'https://1fichier.com/console/index.pl';});</script>
rep:  <script type="text/javascript" src="https://alterupload.com/setcookie.pl?SID=bJcqri4xgqO7lJWkGYKwqowvA=wfVs919wkY6dGgUq6sbarnTmSV27DsjuCC0cFe&lt=1"></script>
rep:  <script type="text/javascript" src="https://cjoint.net/setcookie.pl?SID=bJcqri4xgqO7lJWkGYKwqowvA=wfVs919wkY6dGgUq6sbarnTmSV27DsjuCC0cFe&lt=1"></script>
rep:  <script type="text/javascript" src="https://desfichiers.com/setcookie.pl?SID=bJcqri4xgqO7lJWkGYKwqowvA=wfVs919wkY6dGgUq6sbarnTmSV27DsjuCC0cFe&lt=1"></script>
rep:  <script type="text/javascript" src="https://dfichiers.com/setcookie.pl?SID=bJcqri4xgqO7lJWkGYKwqowvA=wfVs919wkY6dGgUq6sbarnTmSV27DsjuCC0cFe&lt=1"></script>
rep:  <script type="text/javascript" src="https://megadl.fr/setcookie.pl?SID=bJcqri4xgqO7lJWkGYKwqowvA=wfVs919wkY6dGgUq6sbarnTmSV27DsjuCC0cFe&lt=1"></script>
rep:  <script type="text/javascript" src="https://mesfichiers.org/setcookie.pl?SID=bJcqri4xgqO7lJWkGYKwqowvA=wfVs919wkY6dGgUq6sbarnTmSV27DsjuCC0cFe&lt=1"></script>
rep:  <script type="text/javascript" src="https://piecejointe.net/setcookie.pl?SID=bJcqri4xgqO7lJWkGYKwqowvA=wfVs919wkY6dGgUq6sbarnTmSV27DsjuCC0cFe&lt=1"></script>
rep:  <script type="text/javascript" src="https://pjointe.com/setcookie.pl?SID=bJcqri4xgqO7lJWkGYKwqowvA=wfVs919wkY6dGgUq6sbarnTmSV27DsjuCC0cFe&lt=1"></script>
rep:  <script type="text/javascript" src="https://tenvoi.com/setcookie.pl?SID=bJcqri4xgqO7lJWkGYKwqowvA=wfVs919wkY6dGgUq6sbarnTmSV27DsjuCC0cFe&lt=1"></script>
rep:  <script type="text/javascript" src="https://dl4free.com/setcookie.pl?SID=bJcqri4xgqO7lJWkGYKwqowvA=wfVs919wkY6dGgUq6sbarnTmSV27DsjuCC0cFe&lt=1"></script>
rep:</head>
rep:<body>
rep:<div id="header" class="bloc">
rep:	<div class="center-container">
rep:		<a href="https://1fichier.com" title="1fichier.com"><img id="logo" src="https://img.1fichier.com/logo.png" alt="logo" width="240" height="70" style="margin-top:5px" /></a>
rep:
rep:		<div id="btn-container">
rep:			<div class="select-container ddh" style="width:150px">
rep:    		<select class="dropdown" onchange="window.location.href=this.value">
rep:		      <option value="/login.pl?lg=fr" data-imagesrc="https://img.1fichier.com/flags/fr.png">Francais</option>
rep:    		  <option value="/login.pl?lg=bg" data-imagesrc="https://img.1fichier.com/flags/bg.png">Български</option>
rep:		      <option value="/login.pl?lg=cn" data-imagesrc="https://img.1fichier.com/flags/cn.png">中文（简体）</option>
rep:		      <option value="/login.pl?lg=en" data-imagesrc="https://img.1fichier.com/flags/en.png" selected="selected">English</option>
rep:		      <option value="/login.pl?lg=es" data-imagesrc="https://img.1fichier.com/flags/es.png">Español</option>
rep:		      <option value="/login.pl?lg=in" data-imagesrc="https://img.1fichier.com/flags/in.png">हिंदी</option>
rep:		      <option value="/login.pl?lg=pl" data-imagesrc="https://img.1fichier.com/flags/pl.png">Polski</option>
rep:					<option value="/login.pl?lg=pt" data-imagesrc="https://img.1fichier.com/flags/pt.png">Português</option>
rep:		      <option value="/login.pl?lg=tr" data-imagesrc="https://img.1fichier.com/flags/tr.png">Türkçe</option>
rep:					<option value="/login.pl?lg=ru" data-imagesrc="https://img.1fichier.com/flags/ru.png">Русский</option>
rep:		    </select>
rep:			</div>
rep:
rep:			<a class="btn-general btn-gris-clair" href="https://1fichier.com/tarifs.html" title="Prices">Prices</a>
rep:
rep:			
rep:				<div class="select-container ddh" style="width:280px">
rep:					<select class="dropdown" onchange="window.location=this.value">
rep:						<option value="https://1fichier.com/console/index.pl"  >kishibasensei-info@yahoo.fr</option>
rep:						<option value="https://1fichier.com/console/index.pl?mf">My files</option>
rep:						<option value="https://1fichier.com/console/details.pl">My Informations</option>
rep:						<option value="https://1fichier.com/console/ftpmode.pl">FTP Publication</option>
rep:						<option value="https://1fichier.com/console/remote.pl">Remote Upload</option>
rep:						<option value="https://1fichier.com/console/params.pl">Account Parameters</option>
rep:						<option value="https://1fichier.com/console/abo.pl">Premium Services</option>
rep:            <option value="https://1fichier.com/console/com.pl">Commercial</option>
rep:						<option value="https://1fichier.com/logout.pl">Logout</option>
rep:					</select>
rep:				</div>
rep:			
rep:			
rep:		</div>
rep:		<div class="spacer"></div>
rep:	</div>
rep:</div>
rep:
rep:<div class="spacer spacer-20"></div>
rep:
rep:<div class="center-container2">
rep:  <div class="bloc alc">
rep:    <div class="inner">
rep:		  <span class="spacer spacer-20"></span>
rep:    	Vous êtes connecté. Cette page va se raffraichir automatiquement.
rep:			<br/>Si rien ne se produit, veuillez cliquer <a href="https://1fichier.com/console/index.pl">ici</a>.
rep:			<br/>
rep:	    <br/>You are logged in. This page will redirect you.
rep:			<br/>If nothing happens, click <a href="https://1fichier.com/console/index.pl">here</a>.
rep:		  <span class="spacer spacer-20"></span>
rep:   </div>
rep:  </div>
rep:  <span class="spacer spacer-20"></span>
rep:</div>
rep:<div id="footer">
rep:	<div class="center-container">
rep:		<a href="https://1fichier.com" title="Back to home page"><img class="gauche" src="https://img.1fichier.com/logo-footer.png" alt="1fichier.com" /></a>
rep:		<div id="link-container">
rep:			<a href="https://1fichier.com/legal.html">Legal</a><span class="separation"> | </span>
rep:			<a href="https://1fichier.com/cgu.html">Terms Of Use</a><span class="separation"> | </span>
rep:			<a href="https://1fichier.com/abus.html">Abuse</a><span class="separation"> | </span>			
rep:			<a href="https://1fichier.com/tarifs.html">Prices</a><span class="separation"> | </span>
rep:			<a href="https://1fichier.com/revendeurs.html">Resellers</a><span class="separation"> | </span>
rep:			<a href="https://1fichier.com/hlp.html">Help</a><span class="separation"> | </span>
rep:			<a href="https://1fichier.com/network.html">Network</a>
rep:			<br/><a href="https://1fichier.com/contact.html">Contact</a><span class="separation"> | </span>
rep:			<a target="_new" href="https://twitter.com/1fichiercom">Twitter</a><span class="separation"> | </span>
rep:			<a target="_new" href="https://dstorage.fr">DStorage SAS © 2009-2015</a>
rep:		</div>
rep:	</div>
rep:	<span class="spacer"></span>
rep:</div>       
rep:
rep:
rep:<script type="text/javascript">
rep:  var _paq = _paq || [];
rep:  _paq.push(["setCookieDomain", "*.1fichier.com"]);
rep:  _paq.push(["setDoNotTrack", true]);
rep:  _paq.push(['trackPageView']);
rep:  _paq.push(['enableLinkTracking']);
rep:  (function() {
rep:    var u="//st-1.1fichier.com/";
rep:    _paq.push(['setTrackerUrl', u+'piwik.php']);
rep:    _paq.push(['setSiteId', 2]);
rep:    var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
rep:    g.type='text/javascript'; g.async=true; g.defer=true; g.src=u+'piwik.js'; s.parentNode.insertBefore(g,s);
rep:  })();
rep:</script>
rep:<noscript><p><img src="//st-1.1fichier.com/piwik.php?idsite=2" style="border:0;" alt="" /></p></noscript>
rep:
rep:
rep:</body>
rep:</html>
rep: === CURL END ===
rep: === COOKIE BEGIN ===
rep:# Netscape HTTP Cookie File
rep:# http://curl.haxx.se/docs/http-cookies.html
rep:# This file was generated by libcurl! Edit at your own risk.
rep:
rep:.1fichier.com	TRUE	/	FALSE	1477568201	LG	en
rep:.1fichier.com	TRUE	/	FALSE	1448620601	SID	bJcqri4xgqO7lJWkGYKwqowvA=wfVs919wkY6dGgUq6sbarnTmSV27DsjuCC0cFe
rep: === COOKIE END ===
dbg: storage_set: `cookie_file' set for module `1fichier'
dbg: session (new): 'bJcqri4xgqO7lJWkGYKwqowvA=wfVs919wkY6dGgUq6sbarnTmSV27DsjuCC0cFe'
rep: --insecure --compressed --speed-time 600 --connect-timeout 240 --user-agent Mozilla/5.0 (X11; Linux x86_64; rv:6.0) Gecko/20100101 Firefox/6.0 --silent --head -b /media/STORAGE/download/tmp/plowdown.9489.17028 https://1fichier.com/?84sr8se6tj
rep: Received 251 bytes. DRETVAL=0
rep: === CURL BEGIN ===
rep:HTTP/1.1 302 Found
rep:Server: nginx
rep:Date: Wed, 28 Oct 2015 09:36:42 GMT
rep:Content-Type: text/html; charset=utf-8
rep:Connection: keep-alive
rep:Cache-Control: no-cache
rep:Expires: Fri, 30 Oct 1998 14:19:41 GMT
rep:Location: https://c-7.1fichier.com/c1868115825
rep:
rep: === CURL END ===
rep: --insecure --compressed --speed-time 600 --connect-timeout 240 --user-agent Mozilla/5.0 (X11; Linux x86_64; rv:6.0) Gecko/20100101 Firefox/6.0 --silent --form-string links[]=https://1fichier.com/?84sr8se6tj https://1fichier.com/check_links.pl
rep: Received 123 bytes. DRETVAL=0
rep: === CURL BEGIN ===
rep:https://1fichier.com/?84sr8se6tj;Fantastic.Four.2015.FRENCH.720p.BluRay.x264-ShowFr.zone-telechargement.com.mkv;3897678305
rep: === CURL END ===
File URL: https://c-7.1fichier.com/c1868115825
Filename: Fantastic.Four.2015.FRENCH.720p.BluRay.x264-ShowFr.zone-telechargement.com.mkv
rep: --insecure --compressed --speed-time 600 --connect-timeout 240 --user-agent Mozilla/5.0 (X11; Linux x86_64; rv:6.0) Gecko/20100101 Firefox/6.0 -C - --fail --globoff -w %{http_code}\t%{size_download} -o /media/STORAGE/download/tmp/Fantastic.Four.2015.FRENCH.720p.BluRay.x264-ShowFr.zone-telechargement.com.mkv https://c-7.1fichier.com/c1868115825

**Comment by Alexis38** [comment]
The basic command plowdown work it ?

**Comment by juanlucky** [comment]
Here a simpler cmd

plowdown -a user:xxxx https://bk6m
gr.1fichier.com/ -v4 &> debug.log

And its result :

rep: === SYSTEM INFO BEGIN ===
rep: [mach] geexbox armv7 linux-gnueabihf armv7-openbricks-linux-gnueabihf
rep: [bash] 4.3.0(1)-release
rep: [curl] curl 7.34.0 (armv7-openbricks-linux-gnueabihf) libcurl/7.34.0 OpenSSL/1.0.1g zlib/1.2.8
rep: [sed ] This is not GNU sed version 4.0
rep: [lib ] '/root/plowshare4'
rep: === SYSTEM INFO END ===
rep: plowdown version GIT-snapshot
No module found, try simple redirection
rep: --insecure --compressed --speed-time 600 --connect-timeout 240 --silent --user-agent  --head https://bk6mgr.1fichier.com/
rep: Received 247 bytes. DRETVAL=0
rep: === CURL BEGIN ===
rep:HTTP/1.1 200 OK
rep:Server: nginx
rep:Date: Fri, 30 Oct 2015 08:26:25 GMT
rep:Content-Type: text/html; charset=utf-8
rep:Connection: keep-alive
rep:Vary: Accept-Encoding
rep:Cache-Control: no-cache
rep:Expires: Fri, 30 Oct 1998 14:19:41 GMT
rep:Content-Encoding: gzip
rep:
rep: === CURL END ===
dbg: remote server reply: HTTP/1.1 200 OK
Skip: no module for URL (https://bk6mgr.1fichier.com/)

**Comment by juanlucky** [comment]
By the way, an anonymous dl doesn't work either :

# plowdown https://bk6mgr.1fichier.com/ -v4
rep: === SYSTEM INFO BEGIN ===
rep: [mach] geexbox armv7 linux-gnueabihf armv7-openbric
ks-linux-gnueabihf
rep: [bash] 4.3.0(1)-release
rep: [curl] curl 7.34.0 (armv7-openbricks-linux-gnueabih
f) libcurl/7.34.0 OpenSSL/1.0.1g zlib/1.2.8
rep: [sed ] This is not GNU sed version 4.0
rep: [lib ] '/root/plowshare4'
rep: === SYSTEM INFO END ===
rep: plowdown version GIT-snapshot
No module found, try simple redirection
rep: --insecure --compressed --speed-time 600 --connect-
timeout 240 --silent --user-agent  --head https://bk6mgr
.1fichier.com/
rep: Received 247 bytes. DRETVAL=0
rep: === CURL BEGIN ===
rep:HTTP/1.1 200 OK
rep:Server: nginx
rep:Date: Fri, 30 Oct 2015 08:31:28 GMT
rep:Content-Type: text/html; charset=utf-8
rep:Connection: keep-alive
rep:Vary: Accept-Encoding
rep:Cache-Control: no-cache
rep:Expires: Fri, 30 Oct 1998 14:19:41 GMT
rep:Content-Encoding: gzip
rep:
rep: === CURL END ===
dbg: remote server reply: HTTP/1.1 200 OK
Skip: no module for URL (https://bk6mgr.1fichier.com/)
#

**Comment by Alexis38** [comment]
Tests the command without the V4

**Comment by juanlucky** [comment]
The same 

# plowdown https://bk6mgr.1fichier.com/
No module found, try simple redirection
Skip: no module for URL (https://bk6mgr.1fichier.com/)

**Comment by juanlucky** [comment]
Also tried with authentied plowdown (-a) and same result

**Comment by Alexis38** [comment]
Please download and update the files :
- core.sh
- delete.sh
- download.sh
- list.sh
- probe.sh
- upload.sh

- modules\1fichier.sh

Please to verify if the directory for the modules is : {USER}/.config/plowshare/modules

**Comment by juanlucky** [comment]
Works with both url formats now.
Thanks a lot Axel.

**Comment by Alexis38** [comment]
For nothingto the pleasure

**Comment by juanlucky** [comment]
*Alexis (sorry)

**Comment by Alexis38** [comment]
No problem, it's Ok ^^
